create table T_PROCESS_EXPORT_REQUEST (
	id INTEGER NOT NULL PRIMARY KEY,
	process_id INTEGER NOT NULL,
	user_id INTEGER NOT NULL,
	settings VARCHAR(2048) NOT NULL,
	state CHAR DEFAULT 'R' NOT NULL,
	notes VARCHAR(4000),
	requested TIMESTAMP
);

ALTER TABLE T_PROCESS_EXPORT_REQUEST ADD FOREIGN KEY (process_id) REFERENCES T_PROCESS (id);
ALTER TABLE T_PROCESS_EXPORT_REQUEST ADD FOREIGN KEY (user_id) REFERENCES T_USER (id);

CREATE SEQUENCE S_PROCESS_EXPORT_REQUEST_ID MINVALUE 1 MAXVALUE 9999999999 START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

exit;