CREATE TABLE T_USER_PERMISSION 
(
  ID NUMBER NOT NULL 
, USER_ID NUMBER NOT NULL 
, RECEIVER_ID NUMBER NOT NULL 
, SENDER_ID NUMBER NOT NULL 
, PERMISSION NUMBER 
, CONSTRAINT T_USER_PERMISSION_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

  CREATE TABLE T_PERMISSION
   (	ID NUMBER NOT NULL ENABLE, 
	PERMISSION VARCHAR2(20 BYTE), 
	 CONSTRAINT T_PERMISSION_PK PRIMARY KEY (ID)
   ) ;

ALTER TABLE T_USER_PERMISSION ADD FOREIGN KEY (user_id) REFERENCES T_USER (id);

CREATE SEQUENCE S_USER_PERMISSION_ID  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;


Insert into T_PERMISSION (ID,PERMISSION) values (1,'view');
Insert into T_PERMISSION (ID,PERMISSION) values (2,'submit');
