<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p-toast_msg</name>
   <tag></tag>
   <elementGuidId>558e9613-4c35-4c82-acd3-2bf6b42c5ca3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>p-toastitem</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>p-toastitem</value>
   </webElementProperties>
</WebElementEntity>
