ALTER TABLE T_SCHEDULED_SUBMISSION ADD predecessor_sch_sub_id INTEGER;
ALTER TABLE T_SCHEDULED_SUBMISSION ADD FOREIGN KEY (predecessor_sch_sub_id) REFERENCES T_SCHEDULED_SUBMISSION (id);

ALTER TABLE T_SCHEDULE_DEF ADD predecessor_submission_id INTEGER;
ALTER TABLE T_SCHEDULE_DEF ADD FOREIGN KEY (predecessor_submission_id) REFERENCES T_SCHEDULED_SUBMISSION (id);