ALTER TABLE T_SCHEDULE_DEF DROP COLUMN CRITICAL_DATE;

  CREATE TABLE "SPOTLIGHT"."T_SCHEDULE_CRITICAL_DEF" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"PROCESS_ID" NUMBER(*,0), 
	"SETTINGS" VARCHAR2(4000 BYTE), 
	"SCHEDULE_CHANGE_FLAG" CHAR(1 BYTE), 
	"SCHEDULE_START_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"SCHEDULE_END_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"RECURRENCE_PATTERN" CHAR(1 BYTE) DEFAULT 'D' NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 FOREIGN KEY ("PROCESS_ID")
	  REFERENCES "SPOTLIGHT"."T_PROCESS" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE SEQUENCE S_SCHEDULE_CRITICAL_DEF_ID MINVALUE 1 MAXVALUE 9999999999 START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
