CREATE SEQUENCE S_SUBMISSION_NOTIFICATION_ID INCREMENT BY 1 START WITH 1 MAXVALUE 9999999 MINVALUE 1 NOCACHE;

CREATE SEQUENCE S_SUBMISSION_STEP_NOTIF_ID INCREMENT BY 1 START WITH 1 MAXVALUE 9999999 MINVALUE 1 NOCACHE;

ALTER TABLE T_PROCESS_STEP
ADD (
    duration INTEGER DEFAULT 0,
    required CHAR(1) DEFAULT 'N');