INSERT INTO T_STAGE VALUES (S_STAGE_ID.nextVal, 'Transactional S/L Tier');
INSERT INTO T_STAGE VALUES (S_STAGE_ID.nextVal, 'General Ledger Tier');
INSERT INTO T_STAGE VALUES (S_STAGE_ID.nextVal, 'Consolidation Tier');

INSERT INTO T_PROCESS_TYPE VALUES (S_PROCESS_TYPE_ID.nextVal, 'Cash &' || ' Bank');
INSERT INTO T_PROCESS_TYPE VALUES (S_PROCESS_TYPE_ID.nextVal, 'Commercial');
INSERT INTO T_PROCESS_TYPE VALUES (S_PROCESS_TYPE_ID.nextVal, 'Travel, Comp &' || ' Ben');
INSERT INTO T_PROCESS_TYPE VALUES (S_PROCESS_TYPE_ID.nextVal, 'Intercompany');
INSERT INTO T_PROCESS_TYPE VALUES (S_PROCESS_TYPE_ID.nextVal, 'Supply Chain');
INSERT INTO T_PROCESS_TYPE VALUES (S_PROCESS_TYPE_ID.nextVal, 'Capital Assets');
INSERT INTO T_PROCESS_TYPE VALUES (S_PROCESS_TYPE_ID.nextVal, 'Closing &' || ' Reporting');
INSERT INTO T_PROCESS_TYPE VALUES (S_PROCESS_TYPE_ID.nextVal, 'Tax');
INSERT INTO T_PROCESS_TYPE VALUES (S_PROCESS_TYPE_ID.nextVal, 'Stat');

INSERT INTO T_STATUS VALUES (S_STATUS_ID.nextVal, 'in progress');
INSERT INTO T_STATUS VALUES (S_STATUS_ID.nextVal, 'success');
INSERT INTO T_STATUS VALUES (S_STATUS_ID.nextVal, 'warning');
INSERT INTO T_STATUS VALUES (S_STATUS_ID.nextVal, 'failed');
INSERT INTO T_STATUS VALUES (S_STATUS_ID.nextVal, 'fatal');

INSERT INTO T_USER VALUES (S_USER_ID.nextVal, 212584123, 'Jamie Myers');
INSERT INTO T_USER VALUES (S_USER_ID.nextVal, 212628140, 'Cadence Daniels');
INSERT INTO T_USER VALUES (S_USER_ID.nextVal, 212554716, 'Enrique Marron');
INSERT INTO T_USER VALUES (S_USER_ID.nextVal, 212695020, 'Diego Flores');

INSERT INTO T_ROLE VALUES (S_ROLE_ID.nextVal, 'admin');
INSERT INTO T_ROLE VALUES (S_ROLE_ID.nextVal, 'user');
INSERT INTO T_ROLE VALUES (S_ROLE_ID.nextVal, 'application');

INSERT INTO T_USER_ROLE VALUES (1, 1);
INSERT INTO T_USER_ROLE VALUES (2, 1);
INSERT INTO T_USER_ROLE VALUES (3, 1);
INSERT INTO T_USER_ROLE VALUES (4, 1);

exit;